# Generated by Django 5.0.6 on 2024-06-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("name",), "verbose_name_plural": "dishes"},
        ),
    ]
